import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useActiveTenant, useTenant } from "../tenant/TenantProvider";
import { db } from "../lib/supabase";
import { Badge, Button, Card, Field, Icon, inputClass } from "../components/ui";

type Topic = { id: string; name: string; keywords: string[]; is_active: boolean; created_at: string };
type Finding = { id: string; topic_id: string; provider: "tavily" | "searchapi"; canonical_url: string; source_name: string | null; title: string; published_at: string | null; summary: string; relevance_reason: string; discovered_at: string; expires_at: string };

const keywordList = (value: string) => [...new Set(value.split(/[\n,;]+/).map((word) => word.trim()).filter(Boolean))];
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("es-AR", { dateStyle: "medium" }).format(new Date(value)) : "Sin fecha";

export function ContentStudio() {
  const { tenant } = useActiveTenant(); const { can } = useTenant(); const qc = useQueryClient();
  const [topicOpen, setTopicOpen] = useState(false); const [editingTopic, setEditingTopic] = useState<Topic | null>(null); const [topicName, setTopicName] = useState(""); const [keywords, setKeywords] = useState(""); const [topicError, setTopicError] = useState<string | null>(null); const [discoveryError, setDiscoveryError] = useState<string | null>(null);
  const { data: topics = [], isLoading: loadingTopics } = useQuery({ queryKey: ["content-topics", tenant.id], queryFn: async () => { const { data, error } = await db().from("content_topics").select("id,name,keywords,is_active,created_at").eq("tenant_id", tenant.id).order("created_at"); if (error) throw error; return (data ?? []) as Topic[]; } });
  const { data: findings = [], isLoading: loadingFindings } = useQuery({ queryKey: ["content-findings", tenant.id], queryFn: async () => { const { data, error } = await db().from("content_findings").select("id,topic_id,provider,canonical_url,source_name,title,published_at,summary,relevance_reason,discovered_at,expires_at").eq("tenant_id", tenant.id).eq("status", "active").gt("expires_at", new Date().toISOString()).order("discovered_at", { ascending: false }); if (error) throw error; return (data ?? []) as Finding[]; } });
  const saveTopic = useMutation({ mutationFn: async () => { const parsed = keywordList(keywords); if (!topicName.trim()) throw new Error("Indicá el nombre del tema."); if (parsed.length < 5 || parsed.length > 10) throw new Error("Cada tema necesita entre 5 y 10 palabras clave."); if (!editingTopic && topics.filter((topic) => topic.is_active).length >= 5) throw new Error("Ya tenés 5 temas activos. Pausá uno antes de crear otro."); const values = { tenant_id: tenant.id, name: topicName.trim(), keywords: parsed, is_active: true }; const request = editingTopic ? db().from("content_topics").update(values).eq("id", editingTopic.id).eq("tenant_id", tenant.id) : db().from("content_topics").insert(values); const { error } = await request; if (error) throw error; }, onSuccess: () => { setTopicOpen(false); setEditingTopic(null); setTopicName(""); setKeywords(""); setTopicError(null); void qc.invalidateQueries({ queryKey: ["content-topics", tenant.id] }); }, onError: (error) => setTopicError(error instanceof Error ? error.message : "No se pudo guardar el tema.") });
  const toggleTopic = useMutation({ mutationFn: async (topic: Topic) => { if (!topic.is_active && topics.filter((item) => item.is_active).length >= 5) throw new Error("Ya hay 5 temas activos."); const { error } = await db().from("content_topics").update({ is_active: !topic.is_active }).eq("id", topic.id).eq("tenant_id", tenant.id); if (error) throw error; }, onSuccess: () => void qc.invalidateQueries({ queryKey: ["content-topics", tenant.id] }), onError: (error) => setTopicError(error instanceof Error ? error.message : "No se pudo actualizar el tema.") });
  const deleteTopic = useMutation({ mutationFn: async (topic: Topic) => { const { error } = await db().from("content_topics").delete().eq("id", topic.id).eq("tenant_id", tenant.id); if (error) throw error; }, onSuccess: () => { void qc.invalidateQueries({ queryKey: ["content-topics", tenant.id] }); void qc.invalidateQueries({ queryKey: ["content-findings", tenant.id] }); } });
  const discover = useMutation({ mutationFn: async () => { const { data, error } = await db().functions.invoke("discover-content-trends", { body: { tenantId: tenant.id } }); if (error) throw error; if (data?.error) throw new Error(data.error); return data as { inserted: number }; }, onSuccess: () => { setDiscoveryError(null); void qc.invalidateQueries({ queryKey: ["content-findings", tenant.id] }); }, onError: (error) => setDiscoveryError(error instanceof Error ? error.message : "No se pudieron buscar tendencias.") });
  const activeTopics = topics.filter((topic) => topic.is_active);
  const openNewTopic = () => { setEditingTopic(null); setTopicName(""); setKeywords(""); setTopicError(null); setTopicOpen(true); };
  const openEditTopic = (topic: Topic) => { setEditingTopic(topic); setTopicName(topic.name); setKeywords(topic.keywords.join("\n")); setTopicError(null); setTopicOpen(true); };

  return <div className="flex flex-col gap-space-lg pb-12">
    <div className="flex flex-col gap-space-md lg:flex-row lg:items-start lg:justify-between"><div><span className="font-label-sm text-xs font-semibold text-secondary bg-secondary-fixed/40 px-2 py-0.5 rounded-full uppercase">Release 3 · Content Studio</span><h1 className="mt-2 font-headline text-headline-lg font-bold">Content Studio</h1><p className="text-body-md text-on-surface-variant">Descubrí tendencias y prepará contenido comercial relevante para {tenant.name}.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" icon="settings" disabled>Templates por red</Button><Button icon="add" disabled>Nuevo contenido</Button></div></div>
    <Card className="flex flex-col gap-space-md"><div className="flex flex-col gap-space-md border-b border-hairline pb-space-md sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Icon name="topic" className="text-primary"/><h2 className="font-headline text-headline-md font-bold">Temas que seguís</h2></div><p className="mt-1 text-body-sm text-on-surface-variant">Cada tema usa entre 5 y 10 palabras clave. Se consultan hasta 5 temas activos por búsqueda.</p></div><Button icon="add" disabled={!can("admin")} onClick={openNewTopic}>Agregar tema</Button></div>{loadingTopics ? <p className="text-body-sm text-outline">Cargando temas…</p> : <div className="grid gap-space-sm md:grid-cols-2 xl:grid-cols-3">{topics.map((topic) => <div key={topic.id} className="rounded-xl border border-hairline bg-surface-container-low p-space-md"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold">{topic.name}</p><p className="mt-1 text-body-sm text-on-surface-variant">{topic.keywords.length} palabras clave</p></div><Badge tone={topic.is_active ? "verified" : "neutral"}>{topic.is_active ? "Activo" : "Pausado"}</Badge></div><p className="mt-3 line-clamp-2 text-body-sm text-on-surface-variant">{topic.keywords.join(" · ")}</p>{can("admin") && <div className="mt-space-md flex gap-2"><Button className="flex-1" variant="secondary" icon="edit" onClick={() => openEditTopic(topic)}>Editar</Button><button type="button" className="rounded-lg border border-hairline px-3 text-outline hover:bg-surface-container" title={topic.is_active ? "Pausar" : "Activar"} onClick={() => toggleTopic.mutate(topic)}><Icon name={topic.is_active ? "pause" : "play_arrow"}/></button><button type="button" className="rounded-lg border border-hairline px-3 text-error hover:bg-error-container" title="Eliminar" onClick={() => { if (window.confirm(`¿Eliminar el tema “${topic.name}” y sus hallazgos?`)) deleteTopic.mutate(topic); }}><Icon name="delete"/></button></div>}</div>)}{!topics.length && <div className="col-span-full py-8 text-center"><Icon name="topic" className="text-4xl text-outline"/><p className="mt-2 font-semibold">Todavía no hay temas</p><p className="text-body-sm text-on-surface-variant">Creá hasta cinco temas activos para comenzar a detectar oportunidades.</p></div>}</div>}</Card>
    <Card className="flex flex-col gap-space-md"><div className="flex flex-col gap-space-md border-b border-hairline pb-space-md sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Icon name="insights" className="text-primary"/><h2 className="font-headline text-headline-md font-bold">Radar de tendencias</h2></div><p className="mt-1 text-body-sm text-on-surface-variant">Hasta 2 hallazgos nuevos de Tavily y 2 de SearchApi.io por tema. Los hallazgos vencen a los 7 días.</p></div><Button variant="secondary" loading={discover.isPending} disabled={!can("admin") || !activeTopics.length} icon="refresh" onClick={() => discover.mutate()}>Buscar tendencias ahora</Button></div>{discoveryError && <p className="text-body-sm text-error">{discoveryError}</p>}{discover.data && <p className="rounded-lg bg-secondary-fixed/30 px-3 py-2 text-body-sm text-secondary">Se agregaron {discover.data.inserted} hallazgos nuevos. Los artículos ya existentes no se duplican.</p>}{loadingFindings ? <p className="text-body-sm text-outline">Cargando hallazgos…</p> : <div className="grid gap-gutter md:grid-cols-2">{findings.map((finding) => { const topic = topics.find((item) => item.id === finding.topic_id); return <article key={finding.id} className="flex flex-col rounded-xl border border-hairline bg-surface-container-low p-space-md"><div className="flex items-center justify-between gap-3"><Badge tone={finding.provider === "tavily" ? "ai" : "verified"}>{finding.provider === "tavily" ? "Tavily" : "SearchApi.io"}</Badge><span className="text-label-sm text-outline">{formatDate(finding.published_at ?? finding.discovered_at)}</span></div><h3 className="mt-3 font-headline text-headline-sm font-bold leading-snug">{finding.title}</h3><div className="mt-2 flex flex-wrap gap-2"><Badge tone="neutral">{topic?.name ?? "Tema eliminado"}</Badge>{finding.source_name && <span className="text-body-sm text-on-surface-variant">{finding.source_name}</span>}</div><p className="mt-3 line-clamp-5 text-body-sm text-on-surface-variant">{finding.summary}</p><p className="mt-3 border-t border-hairline pt-3 text-body-sm text-on-surface-variant"><strong className="text-on-surface">Por qué importa: </strong>{finding.relevance_reason}</p><div className="mt-auto flex items-center justify-between gap-2 pt-space-md"><a href={finding.canonical_url} target="_blank" rel="noreferrer" className="text-label-md font-semibold text-primary hover:underline">Ver fuente ↗</a><Button variant="secondary" disabled icon="edit_note">Crear publicación</Button></div></article>; })}{!findings.length && <div className="col-span-full py-10 text-center"><Icon name="travel_explore" className="text-4xl text-outline"/><p className="mt-2 font-semibold">No hay hallazgos vigentes</p><p className="text-body-sm text-on-surface-variant">{activeTopics.length ? "Usá “Buscar tendencias ahora” para descubrir notas nuevas." : "Primero creá y activá un tema."}</p></div>}</div>}</Card>
    {topicOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-space-md"><Card className="w-full max-w-xl"><div className="flex items-start justify-between border-b border-hairline pb-space-md"><div><h2 className="font-headline text-headline-md font-bold">{editingTopic ? "Editar tema" : "Nuevo tema"}</h2><p className="text-body-sm text-on-surface-variant">Los resultados serán privados para {tenant.name}.</p></div><button type="button" className="p-1" onClick={() => setTopicOpen(false)}><Icon name="close"/></button></div><div className="mt-space-lg flex flex-col gap-space-md"><Field label="Tema *"><input value={topicName} onChange={(event) => setTopicName(event.target.value)} className={inputClass} placeholder="Ej.: Agentes de Inteligencia Artificial autónomos"/></Field><Field label="Palabras clave *" hint={`${keywordList(keywords).length}/10 · Ingresá de 5 a 10, una por línea o separadas por coma.`}><textarea value={keywords} onChange={(event) => setKeywords(event.target.value)} className={`${inputClass} h-36 py-2`} placeholder={"agentes autónomos\nIA empresarial\nautomatización comercial\ninteligencia artificial\nventas B2B"}/></Field>{topicError && <p className="text-body-sm text-error">{topicError}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setTopicOpen(false)}>Cancelar</Button><Button type="button" loading={saveTopic.isPending} onClick={() => saveTopic.mutate()}>Guardar tema</Button></div></div></Card></div>}
  </div>;
}
