import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useActiveTenant, useTenant } from "../tenant/TenantProvider";
import { db } from "../lib/supabase";
import { Badge, Button, Card, Field, Icon, inputClass } from "../components/ui";

type Capability = "text" | "image" | "embedding";
type Model = { id: string; name: string; pricing?: { prompt?: string; image?: string } };
const groups = [{ id: "social", title: "Redes sociales", icon: "share", items: "LinkedIn, Instagram, X, Facebook, TikTok", providers: ["LinkedIn", "Instagram", "X", "Facebook", "TikTok"] }, { id: "crm", title: "CRMs", icon: "hub", items: "HubSpot, Monday, CRM propietario", providers: ["HubSpot", "Monday", "CRM propietario"] }, { id: "telephony", title: "Telefonía", icon: "call", items: "Twilio y otros", providers: ["Twilio", "Otro proveedor"] }, { id: "storage", title: "Storage", icon: "cloud", items: "Google Drive, OneDrive, Dropbox", providers: ["Google Drive", "OneDrive", "Dropbox"] }, { id: "messaging", title: "Mensajería", icon: "forum", items: "Telegram, Slack, WhatsApp Business, Teams, SMTP", providers: ["Telegram", "Slack", "WhatsApp Business", "Teams", "SMTP"] }];
const capLabel: Record<Capability, string> = { text: "Texto", image: "Imágenes", embedding: "Embeddings" };
const sections = [{ id: "models", label: "Modelos IA" }, ...groups.map(({ id, title }) => ({ id, label: title }))];

export function Integrations() {
  const { tenant } = useActiveTenant(); const { can } = useTenant(); const qc = useQueryClient();
  const [open, setOpen] = useState(false); const [token, setToken] = useState(""); const [integrationId, setIntegrationId] = useState<string | null>(null); const [models, setModels] = useState<Record<Capability, Model[]>>({ text: [], image: [], embedding: [] }); const [error, setError] = useState<string | null>(null); const [activeSection, setActiveSection] = useState("models");
  const { data: integrations = [] } = useQuery({ queryKey: ["tenant", tenant.id, "integrations"], queryFn: async () => { const { data, error } = await db().from("integrations").select("*").eq("tenant_id", tenant.id); if (error) throw error; return data ?? []; } });
  const { data: configs = [] } = useQuery({ queryKey: ["llm-model-configs", tenant.id], queryFn: async () => { const { data, error } = await db().from("llm_model_configs").select("*").eq("tenant_id", tenant.id); if (error) throw error; return data ?? []; } });
  const openRouter = integrations.find((i) => i.provider === "openrouter");
  const callModels = async (capability: Capability, id?: string, providerToken?: string) => { const { data, error: invokeError } = await db().functions.invoke("llm-models", { body: { tenantId: tenant.id, action: providerToken ? "connect" : "list", provider: "openrouter", integrationId: id, token: providerToken, capability } }); if (invokeError) throw invokeError; if (data?.error) throw new Error(data.error); return data as { integrationId: string; models: Model[] }; };
  const connect = useMutation({ mutationFn: async () => { const first = await callModels("text", integrationId ?? undefined, token || undefined); const id = first.integrationId; const [image, embedding] = await Promise.all([callModels("image", id), callModels("embedding", id)]); return { id, text: first.models, image: image.models, embedding: embedding.models }; }, onSuccess: (data) => { setIntegrationId(data.id); setModels({ text: data.text, image: data.image, embedding: data.embedding }); setToken(""); void qc.invalidateQueries({ queryKey: ["tenant", tenant.id, "integrations"] }); }, onError: (e) => setError(e instanceof Error ? e.message : "No se pudo conectar OpenRouter") });
  const refreshCatalog = useMutation({ mutationFn: async () => { const id = integrationId ?? openRouter?.id; if (!id) throw new Error("Conectá OpenRouter primero"); const [text, image, embedding] = await Promise.all([callModels("text", id), callModels("image", id), callModels("embedding", id)]); return { id, text: text.models, image: image.models, embedding: embedding.models }; }, onSuccess: (data) => { setIntegrationId(data.id); setModels({ text: data.text, image: data.image, embedding: data.embedding }); }, onError: (e) => setError(e instanceof Error ? e.message : "No se pudo actualizar el catálogo") });
  const choose = useMutation({ mutationFn: async ({ capability, slot, model }: { capability: Capability; slot: "primary" | "backup"; model: Model | null }) => { if (!model) { const existing = configs.find((c) => c.capability === capability && c.slot === slot); if (existing) { const { error } = await db().from("llm_model_configs").delete().eq("id", existing.id); if (error) throw error; } return; } const id = integrationId ?? openRouter?.id; if (!id) throw new Error("Conectá OpenRouter primero"); const { error } = await db().from("llm_model_configs").upsert({ tenant_id: tenant.id, integration_id: id, capability, slot, model_id: model.id, model_name: model.name, is_active: true }, { onConflict: "tenant_id,capability,slot" }); if (error) throw error; }, onSuccess: () => void qc.invalidateQueries({ queryKey: ["llm-model-configs", tenant.id] }), onError: (e) => setError(e instanceof Error ? e.message : "No se pudo guardar el modelo") });
  const modalClose = () => { setOpen(false); setError(null); setToken(""); };
  const selectedGroup = groups.find((group) => group.id === activeSection);
  return <div className="flex flex-col gap-space-lg pb-12"><div className="flex flex-col gap-space-md xl:flex-row xl:items-start xl:justify-between"><div><span className="font-label-sm text-xs font-semibold text-secondary bg-secondary-fixed/40 px-2 py-0.5 rounded-full uppercase">Integraciones</span><h1 className="mt-2 font-headline text-headline-lg font-bold">Ecosistema conectado</h1><p className="text-body-md text-on-surface-variant">Conectá proveedores por categoría. Las credenciales siempre se almacenan cifradas.</p></div><nav aria-label="Secciones de integraciones" className="flex max-w-full gap-2 overflow-x-auto pb-1 xl:justify-end">{sections.map((section) => <button key={section.id} type="button" aria-current={activeSection === section.id ? "page" : undefined} onClick={() => setActiveSection(section.id)} className={`shrink-0 rounded-lg border px-3 py-2 text-label-md transition-colors ${activeSection === section.id ? "border-primary bg-primary text-on-primary" : "border-primary bg-surface-container-lowest text-primary hover:bg-primary-fixed"}`}>{section.label}</button>)}</nav></div>
    {activeSection === "models" ? <Card className="flex flex-col gap-space-lg"><div className="flex flex-col md:flex-row md:items-center justify-between gap-space-md border-b border-hairline pb-space-md"><div><div className="flex gap-2 items-center"><Icon name="neurology" className="text-primary"/><h2 className="font-headline text-headline-md font-bold">Modelos de IA</h2></div><p className="text-body-sm text-on-surface-variant mt-1">Texto, imágenes y embeddings con principal y respaldo independientes.</p></div>{openRouter?.status === "connected" ? <div className="flex items-center gap-2"><Badge tone="verified" icon="check_circle">OpenRouter conectado</Badge><Button variant="secondary" loading={refreshCatalog.isPending} disabled={!can("admin")} icon="refresh" onClick={() => refreshCatalog.mutate()}>Actualizar catálogo</Button></div> : <Button disabled={!can("admin")} icon="key" onClick={() => setOpen(true)}>Conectar OpenRouter</Button>}</div>
      {(["text", "image", "embedding"] as Capability[]).map((cap) => { const primary = configs.find((c) => c.capability === cap && c.slot === "primary"); const backup = configs.find((c) => c.capability === cap && c.slot === "backup"); const list = models[cap]; return <div key={cap} className="grid md:grid-cols-[160px_1fr_1fr] gap-space-md rounded-xl bg-surface-container-low p-space-md"><div><p className="font-semibold">{capLabel[cap]}</p><p className="text-body-sm text-on-surface-variant">{cap === "embedding" ? "RAG y búsqueda" : cap === "image" ? "Assets de contenido" : "Agentes y contenido"}</p></div>{(["primary", "backup"] as const).map((slot) => { const selected = slot === "primary" ? primary : backup; return <Field key={slot} label={slot === "primary" ? "Principal" : "Backup opcional"}><select disabled={!openRouter || !can("admin") || choose.isPending} value={selected?.model_id ?? ""} onChange={(e) => choose.mutate({ capability: cap, slot, model: list.find((m) => m.id === e.target.value) ?? null })} className={inputClass}><option value="">{openRouter ? "Sin modelo" : "Conectá OpenRouter"}</option>{list.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select>{selected?.health === "unhealthy" && <span className="text-body-sm text-error">No responde: se usará el backup.</span>}</Field>; })}</div>; })}</Card> : selectedGroup && <Card className="flex flex-col gap-space-lg"><div className="flex items-start justify-between gap-space-md border-b border-hairline pb-space-md"><div><div className="flex items-center gap-2"><Icon name={selectedGroup.icon} className="text-primary"/><h2 className="font-headline text-headline-md font-bold">{selectedGroup.title}</h2></div><p className="mt-1 text-body-sm text-on-surface-variant">Configurá los proveedores de esta categoría. Las conexiones estarán disponibles próximamente.</p></div><Badge tone="neutral">Próximamente</Badge></div><div className="grid gap-gutter md:grid-cols-2 xl:grid-cols-3">{selectedGroup.providers.map((provider) => <div key={provider} className="rounded-xl border border-hairline bg-surface-container-low p-space-md"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{provider}</p><Badge tone="neutral">Pendiente</Badge></div><p className="mt-2 text-body-sm text-on-surface-variant">La configuración de {provider} se habilitará en una próxima entrega.</p><Button className="mt-space-md w-full" variant="secondary" disabled>Configurar</Button></div>)}</div></Card>}
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-space-md"><Card className="w-full max-w-lg"><div className="flex justify-between border-b border-hairline pb-space-md"><div><h2 className="font-headline text-headline-md font-bold">Conectar OpenRouter</h2><p className="text-body-sm text-on-surface-variant">El token se valida y almacena cifrado; nunca se vuelve a mostrar.</p></div><button onClick={modalClose}><Icon name="close"/></button></div><div className="mt-space-lg flex flex-col gap-space-md"><Field label="API key de OpenRouter"><input type="password" value={token} onChange={(e) => setToken(e.target.value)} className={inputClass} placeholder="sk-or-v1-…"/></Field>{error && <p className="text-body-sm text-error">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={modalClose}>Cancelar</Button><Button type="button" loading={connect.isPending} onClick={() => connect.mutate()} disabled={!token}>Validar y cargar modelos</Button></div></div></Card></div>}
  </div>;
}
