import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useActiveTenant, useTenant } from "../tenant/TenantProvider";
import { db } from "../lib/supabase";
import { Badge, Button, Card, Field, Icon, inputClass } from "../components/ui";

type Capability = "text" | "image" | "embedding";
type Provider = "openrouter" | "gemini" | "openai" | "anthropic" | "deepseek" | "qwen" | "groq" | "cerebras";
type Model = { id: string; name: string; provider: Provider; integrationId: string; capability: Capability[]; isFree: boolean };

const providerOptions: Array<{ id: Provider; label: string }> = [
  { id: "openrouter", label: "OpenRouter" }, { id: "gemini", label: "Google Gemini" }, { id: "openai", label: "OpenAI" }, { id: "anthropic", label: "Anthropic Claude" }, { id: "deepseek", label: "DeepSeek" }, { id: "qwen", label: "Qwen" }, { id: "groq", label: "Groq" }, { id: "cerebras", label: "Cerebras" },
];
const groups = [{ id: "social", title: "Redes sociales", icon: "share", providers: ["LinkedIn", "Instagram", "X", "Facebook", "TikTok"] }, { id: "crm", title: "CRMs", icon: "hub", providers: ["HubSpot", "Monday", "CRM propietario"] }, { id: "telephony", title: "Telefonía", icon: "call", providers: ["Twilio", "Otro proveedor"] }, { id: "storage", title: "Storage", icon: "cloud", providers: ["Google Drive", "OneDrive", "Dropbox"] }, { id: "messaging", title: "Mensajería", icon: "forum", providers: ["Telegram", "Slack", "WhatsApp Business", "Teams", "SMTP"] }];
const sections = [{ id: "models", label: "Modelos IA" }, ...groups.map(({ id, title }) => ({ id, label: title }))];
const capLabel: Record<Capability, string> = { text: "Texto", image: "Imágenes", embedding: "Embeddings" };

export function Integrations() {
  const { tenant } = useActiveTenant(); const { can } = useTenant(); const qc = useQueryClient();
  const [activeSection, setActiveSection] = useState("models"); const [open, setOpen] = useState(false); const [provider, setProvider] = useState<Provider>("openrouter"); const [token, setToken] = useState(""); const [catalog, setCatalog] = useState<Model[]>([]); const [modelSearch, setModelSearch] = useState(""); const [onlyFree, setOnlyFree] = useState(false); const [error, setError] = useState<string | null>(null);
  const { data: integrations = [] } = useQuery({ queryKey: ["tenant", tenant.id, "integrations"], queryFn: async () => { const { data, error } = await db().from("integrations").select("id,provider,status").eq("tenant_id", tenant.id); if (error) throw error; return data ?? []; } });
  const { data: configs = [] } = useQuery({ queryKey: ["llm-model-configs", tenant.id], queryFn: async () => { const { data, error } = await db().from("llm_model_configs").select("*").eq("tenant_id", tenant.id); if (error) throw error; return data ?? []; } });
  const connected = integrations.filter((item) => providerOptions.some((option) => option.id === item.provider) && item.status === "connected");
  const callModels = async (nextProvider: Provider, integrationId?: string, providerToken?: string) => { const { data, error: invokeError } = await db().functions.invoke("llm-models", { body: { tenantId: tenant.id, action: providerToken ? "connect" : "list", provider: nextProvider, integrationId, token: providerToken } }); if (invokeError) throw invokeError; if (data?.error) throw new Error(data.error); return data as { integrationId: string; models: Omit<Model, "integrationId">[] }; };
  const refreshCatalog = useMutation({ mutationFn: async () => { const results = await Promise.allSettled(connected.map(async (item) => { const result = await callModels(item.provider as Provider, item.id); return result.models.map((model) => ({ ...model, integrationId: result.integrationId })); })); return results.flatMap((result) => result.status === "fulfilled" ? result.value : []); }, onSuccess: (models) => { setCatalog(models.sort((a, b) => a.name.localeCompare(b.name, "es"))); setError(null); }, onError: (reason) => setError(reason instanceof Error ? reason.message : "No se pudo actualizar el catálogo") });
  const connect = useMutation({ mutationFn: async () => { const result = await callModels(provider, undefined, token); return result.models.map((model) => ({ ...model, integrationId: result.integrationId })); }, onSuccess: (models) => { setCatalog((current) => [...current.filter((model) => model.provider !== provider), ...models].sort((a, b) => a.name.localeCompare(b.name, "es"))); setToken(""); setOpen(false); setError(null); void qc.invalidateQueries({ queryKey: ["tenant", tenant.id, "integrations"] }); }, onError: (reason) => setError(reason instanceof Error ? reason.message : "No se pudo conectar el proveedor") });
  const choose = useMutation({ mutationFn: async ({ capability, slot, model }: { capability: Capability; slot: "primary" | "backup"; model: Model | null }) => { const existing = configs.find((config) => config.capability === capability && config.slot === slot); if (!model) { if (existing) { const { error } = await db().from("llm_model_configs").delete().eq("id", existing.id); if (error) throw error; } return; } const { error } = await db().from("llm_model_configs").upsert({ tenant_id: tenant.id, integration_id: model.integrationId, capability, slot, model_id: model.id, model_name: model.name, is_active: true }, { onConflict: "tenant_id,capability,slot" }); if (error) throw error; }, onSuccess: () => void qc.invalidateQueries({ queryKey: ["llm-model-configs", tenant.id] }), onError: (reason) => setError(reason instanceof Error ? reason.message : "No se pudo guardar el modelo") });
  const modelsFor = (capability: Capability) => catalog.filter((model) => model.capability.includes(capability) && (!onlyFree || model.isFree) && `${model.name} ${model.id} ${model.provider}`.toLocaleLowerCase().includes(modelSearch.toLocaleLowerCase())).sort((a, b) => a.name.localeCompare(b.name, "es"));
  const selectedGroup = groups.find((group) => group.id === activeSection);
  const connectedLabel = (item: { provider: string }) => providerOptions.find((option) => option.id === item.provider)?.label ?? item.provider;
  return <div className="flex flex-col gap-space-lg pb-12">
    <div className="flex flex-col gap-space-md xl:flex-row xl:items-start xl:justify-between"><div><span className="font-label-sm text-xs font-semibold text-secondary bg-secondary-fixed/40 px-2 py-0.5 rounded-full uppercase">Integraciones</span><h1 className="mt-2 font-headline text-headline-lg font-bold">Ecosistema conectado</h1><p className="text-body-md text-on-surface-variant">Conectá proveedores por categoría. Las credenciales siempre se almacenan cifradas.</p></div><nav aria-label="Secciones de integraciones" className="flex max-w-full gap-2 overflow-x-auto pb-1 xl:justify-end">{sections.map((section) => <button key={section.id} type="button" aria-current={activeSection === section.id ? "page" : undefined} onClick={() => setActiveSection(section.id)} className={`shrink-0 rounded-lg border px-3 py-2 text-label-md transition-colors ${activeSection === section.id ? "border-primary bg-primary text-on-primary" : "border-primary bg-surface-container-lowest text-primary hover:bg-primary-fixed"}`}>{section.label}</button>)}</nav></div>
    {activeSection === "models" ? <Card className="flex flex-col gap-space-lg"><div className="flex flex-col gap-space-md border-b border-hairline pb-space-md"><div className="flex flex-col gap-space-md md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><Icon name="neurology" className="text-primary"/><h2 className="font-headline text-headline-md font-bold">Modelos de IA</h2></div><p className="mt-1 text-body-sm text-on-surface-variant">Conectá proveedores, reuní sus modelos y elegí principal y backup por capacidad.</p></div><div className="flex flex-wrap items-center gap-2"><Button variant="secondary" loading={refreshCatalog.isPending} disabled={!connected.length || !can("admin")} icon="refresh" onClick={() => refreshCatalog.mutate()}>Actualizar catálogo</Button><Button disabled={!can("admin")} icon="add" onClick={() => setOpen(true)}>Conectar proveedor</Button></div></div><div className="flex flex-wrap gap-2">{connected.length ? connected.map((item) => <Badge key={item.id} tone="verified" icon="check_circle">{connectedLabel(item)}</Badge>) : <Badge tone="neutral">Sin proveedores conectados</Badge>}</div></div>
      <div className="grid gap-space-md rounded-xl bg-surface-container-low p-space-md md:grid-cols-[1fr_auto]"><Field label="Buscar modelo"><input value={modelSearch} onChange={(event) => setModelSearch(event.target.value)} className={inputClass} placeholder="Buscar por modelo o proveedor…"/></Field><label className="flex cursor-pointer items-center gap-2 text-label-md font-semibold"><input type="checkbox" checked={onlyFree} onChange={(event) => setOnlyFree(event.target.checked)} className="h-4 w-4 accent-primary"/>Solo gratuitos</label></div>
      {(["text", "image", "embedding"] as Capability[]).map((capability) => { const primary = configs.find((config) => config.capability === capability && config.slot === "primary"); const backup = configs.find((config) => config.capability === capability && config.slot === "backup"); const list = modelsFor(capability); return <div key={capability} className="grid gap-space-md rounded-xl bg-surface-container-low p-space-md md:grid-cols-[160px_1fr_1fr]"><div><p className="font-semibold">{capLabel[capability]}</p><p className="text-body-sm text-on-surface-variant">{capability === "embedding" ? "RAG y búsqueda" : capability === "image" ? "Assets de contenido" : "Agentes y contenido"}</p></div>{(["primary", "backup"] as const).map((slot) => { const selected = slot === "primary" ? primary : backup; return <Field key={slot} label={slot === "primary" ? "Principal" : "Backup opcional"}><select disabled={!connected.length || !can("admin") || choose.isPending} value={selected?.model_id ?? ""} onChange={(event) => choose.mutate({ capability, slot, model: list.find((model) => model.id === event.target.value && model.integrationId === event.target.selectedOptions[0]?.dataset.integration) ?? null })} className={inputClass}><option value="">{connected.length ? catalog.length ? "Sin modelo" : "Actualizá el catálogo" : "Conectá un proveedor"}</option>{list.map((model) => <option key={`${model.integrationId}:${model.id}`} value={model.id} data-integration={model.integrationId}>{model.name} · {providerOptions.find((option) => option.id === model.provider)?.label}{model.isFree ? " · Gratis" : ""}</option>)}</select>{selected?.health === "unhealthy" && <span className="text-body-sm text-error">No responde: se usará el backup.</span>}</Field>; })}</div>; })}</Card> : selectedGroup && <Card className="flex flex-col gap-space-lg"><div className="flex items-start justify-between gap-space-md border-b border-hairline pb-space-md"><div><div className="flex items-center gap-2"><Icon name={selectedGroup.icon} className="text-primary"/><h2 className="font-headline text-headline-md font-bold">{selectedGroup.title}</h2></div><p className="mt-1 text-body-sm text-on-surface-variant">Configurá los proveedores de esta categoría. Las conexiones estarán disponibles próximamente.</p></div><Badge tone="neutral">Próximamente</Badge></div><div className="grid gap-gutter md:grid-cols-2 xl:grid-cols-3">{selectedGroup.providers.map((item) => <div key={item} className="rounded-xl border border-hairline bg-surface-container-low p-space-md"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{item}</p><Badge tone="neutral">Pendiente</Badge></div><p className="mt-2 text-body-sm text-on-surface-variant">La configuración de {item} se habilitará en una próxima entrega.</p><Button className="mt-space-md w-full" variant="secondary" disabled>Configurar</Button></div>)}</div></Card>}
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-space-md"><Card className="w-full max-w-lg"><div className="flex items-start justify-between border-b border-hairline pb-space-md"><div><h2 className="font-headline text-headline-md font-bold">Conectar proveedor de IA</h2><p className="text-body-sm text-on-surface-variant">El token se valida y almacena cifrado; nunca se vuelve a mostrar.</p></div><button onClick={() => { setOpen(false); setError(null); setToken(""); }} className="p-1"><Icon name="close"/></button></div><div className="mt-space-lg flex flex-col gap-space-md"><Field label="Proveedor"><select value={provider} onChange={(event) => setProvider(event.target.value as Provider)} className={inputClass}>{providerOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></Field><Field label="API key"><input type="password" value={token} onChange={(event) => setToken(event.target.value)} className={inputClass} placeholder="Pegá la API key del proveedor"/></Field>{error && <p className="text-body-sm text-error">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancelar</Button><Button type="button" loading={connect.isPending} disabled={!token} onClick={() => connect.mutate()}>Validar y cargar modelos</Button></div></div></Card></div>}
  </div>;
}
